apiVersion: v1
kind: Service
metadata:
  name: mongo-cluster-0-external
  namespace: mongo
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: mongo-cluster-0
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30001

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-cluster-1-external
  namespace: mongo
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: mongo-cluster-1
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30002

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-cluster-2-external
  namespace: mongo
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: mongo-cluster-2
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30003

